### ISSUE TITLE
Game Process Not Responding During Start Up

### ISSUE THREAD

**Issue by qe201020335** [HypersonicSharkz/SmartSongSuggest#1] opened 2022-08-15 16:21 UTC
Apparently, when the internet is not great and some HTTP requests take longer to complete, the main thread is somehow blocked and not responding.

There are no exceptions thrown so I looked up the code.

During `OnStart` it will init the `SongSuggestManager` which will init a `SongSuggest` on the Unity main thread ([code](https://github.com/HypersonicSharkz/SmartSongSuggest/blob/master/TaohSongSuggest/Managers/SongSuggestManager.cs#L55))

The problem is during the initialization of `SongSuggest` it will [UpdateLinkData](https://github.com/HypersonicSharkz/SmartSongSuggest/blob/16de73e54dd25dae0405c78ceaa8c42e2a5f657d/TaohSongSuggest/SongSuggest/DataHandling/SongSuggest.cs#L73) by making HTTP request to github ([code](https://github.com/HypersonicSharkz/SmartSongSuggest/blob/master/TaohSongSuggest/SongSuggest/DataHandling/WebDownloader.cs#L94)) **synchronously**

That means if the requests take a long time to complete, it will somehow block the main thread and make the whole process "Not Responding".

I found this issue because someone in China (where it could take a looong time to make a request to GitHub and may not even succeed) reported that the game is stuck on a black screen and not responding during start-up.

**Comment by TaohRihze** [comment] 2022-08-17 05:49
Thanks for reporting this. We will have a look at what can be done, and you are right, the initialization should be handled outside the main thread if possible. I hope Sharkz can work his magic on the UI side and put the whole backend in a thread on the initialization.

This delay is likely only when there is a new data file (10mb).

**Comment by WGzeyu** [comment] 2022-08-17 06:06
> This delay is likely only when there is a new data file (10mb).

Meanwhile, about 80% of Chinese players' games will remain unresponsive at launch because they can't use GitHub.

**Comment by TaohRihze** [comment] 2022-08-17 06:26
The access to the GitHub is needed for the files, and check if they are updated. That part I would say is working as intended.

I will give it some thoughts if there should be an option to turn the check/update off, and people would have to manually get the updated files if doing so. (could cause issues on rebalances of scores, that the files are not updated often etc.)

**Comment by TaohRihze** [comment] 2022-08-17 06:31
I can see the initialization on file errors would go to the UI part currently, and the mod would not be loaded correct. (intended behaviour).

I will add a note about looking at recovery option so it still continues to function, just with current version of the player data file, and the new file should be grabbed at next startup instead.

**Comment by qe201020335** [comment] 2022-08-17 06:44
I think if we can schedule the whole initialization task ([this](https://github.com/HypersonicSharkz/SmartSongSuggest/blob/master/TaohSongSuggest/Managers/SongSuggestManager.cs#L55-L60) section of the code) of SongSuggest somewhere off the main thread then the issue should be resolved and I don't see a reason why it cannot be done on other threads.

basically change `IPA.Utilities.Async.UnityMainThreadTaskScheduler.Factory.StartNew` to `System.Threading.Tasks.TaskFactory.StartNew`

**Comment by TaohRihze** [comment] 2022-08-17 14:50
The UI had trouble accessing the player ID if not in main thread.

We have changed the code so players data are not loaded on startup, and instead forces a refresh/load when generating songs (as should already be done), and made the code handling of this more consistent.

We will release a fix on the GIT with this once we tested a few more things.

**Comment by TaohRihze** [comment] 2022-08-17 14:54
As for the access to GIT files, I have put it as a new feature for a future release that if file access fails, and there is older data available. This means that if a user cannot access the GIT, the mod should still work if there is a data file.

Users without access to the automatic process will still need to manually get and keep these files updated (Will not suggest new songs if not updated, but suggestions should last unless star ratings are rebalanced). They will need to clear their user cache file if there is a star rating rebalance manual. But overall the users should be able to use the mods functionality.

**Comment by TaohRihze** [comment] 2022-08-18 13:10
A new update is available here https://github.com/HypersonicSharkz/SmartSongSuggest/releases/tag/v1.5.19

Code has been updated to put the startup in its own thread.

Please let me know if the update fixes the problem or not (closing this post for now). Feel free to message me here or on Discord. Taoh#6132

**Closed as completed** 2022-08-18 13:10 UTC
